config/routes.rb
Betastore::Application.routes.draw do
  namespace :admin do
    resources :products
      root :to => 'products#index'

  
  end

  resources :products, only: [:index, :show]

  resources :subscriptions, only: [:new, :create, :show]

  resources :orders do
    resource :refund
  end

  get '/sign_up' => 'customers#new', as: 'sign_up'
  post '/sign_up' => 'customers#create'

   get '/log_in'  => 'log_ins#new', as: 'log_in'
  post '/log_in'  => 'log_ins#create'
  post '/log_out' => 'log_ins#destroy', as: 'log_out'

  root :to => 'subscriptions#new'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  has_many :line_items, :through => :orders
  has_many :products, :through => :line_items
  has_many :password_resets

  validates_presence_of :name, :email

  has_secure_password
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  
  before_validation :set_price
  
  def set_price
    self.price = product.price
  end
  
  def total_price
    quantity * price
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :line_items
  
  def self.recent
    where("placed_at > ?", 7.days.ago)
  end
  
  def self.by(customer)
    where(customer_id: customer.id)
  end
end

app/models/password_reset.rb
class PasswordReset < ActiveRecord::Base
  belongs_to :customer

  before_validation :generate_token
  
  def generate_token
    self.token ||= SecureRandom.hex(16)
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, :through => :line_items
  
  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  
  def image_url
    "/products/#{name.downcase.tr(' ', '_')}.jpg"
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

  # GET /admin/products
  # GET /admin/products.json
  def index
    @admin_products = Admin::Product.all
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Admin::Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @admin_product = Admin::Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to @admin_product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_product }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    respond_to do |format|
      if @admin_product.update(admin_product_params)
        format.html { redirect_to @admin_product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @admin_product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Admin::Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_product_params
      params[:admin_product]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception

  before_filter :require_log_in

  protected
  def require_log_in
    redirect_to '/log_in' unless logged_in?
  end

  helper_method :logged_in?
  def logged_in?
    cookies.signed[:customer_id].present?
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  skip_before_filter :require_log_in, only: [:new, :create]

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to log_in_path, notice: 'Your account was created, please log in'
    else
      render 'new'
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :email, :password)
  end
end

app/controllers/log_ins_controller.rb
class LogInsController < ApplicationController
  skip_before_filter :require_log_in

  def create
    customer = Customer.find_by(email: params[:email])
    if customer && customer.authenticate(params[:password])
      cookies.signed[:customer_id] = customer.id
      redirect_to products_path
    else
      redirect_to log_in_path, alert: 'Log In Failed'
    end
  end

  def destroy
    cookies.delete(:customer_id)
    redirect_to products_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :require_log_in

  def index
    @products = Product.all
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(subscription_params)

    if @subscription.save
      redirect_to @subscription, notice: 'Subscription was successfully created.'
    else
      render action: 'new'        
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:email)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def product_title(product)
    "#{product.name} - ##{product.id}"
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for(@admin_product) do |f| %>
  <% if @admin_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
      <% @admin_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing admin_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Listing admin_products</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_products.each do |admin_product| %>
      <tr>
        <td><%= link_to 'Show', admin_product %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(admin_product) %></td>
        <td><%= link_to 'Destroy', admin_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New admin_product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_product_path(@admin_product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/layouts/_footer.html.erb
<hr />
&copy; Betamore <%= Time.current.year %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Betastore</title>
    <%= stylesheet_link_tag "application", "subscriptions" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= image_tag "logo.jpg", width: 600 %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/log_ins/new.html.erb
<h1>Log In</h1>

<% if flash[:alert] %>
  <p style="color: red"><%= flash[:alert] %></p>
<% end %>

<%= form_tag do %>
  <div>
    <%= label_tag :email %>
    <%= email_field_tag :email %>
  </div>
  
  <div>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  
  <%= button_tag "Log In" %>
<% end %>

<p>Don't have an account yet? <%= link_to "Sign Up", sign_up_path %></p>

app/views/orders/_order.html.erb
<h2>Order Details</h2>

app/views/orders/new.html.erb
<h1><%= @message %></h1>

<%= render 'order' %>

app/views/products/index.html.erb
<% if cookies[:email] %>
  <%= link_to "Log Out", log_out_path, method: 'post' %>
<% else %>
  <%= link_to "Log In", log_in_path %>
<% end %>

<section class="products">
  <% @products.each do |product| %>
    <article>
      <%= image_tag product.image_url %>
      <h2><%= link_to product_title(product), product_path(product) %></h2>
      <p>
        <%= number_to_currency product.price %>,
        Added <%= time_ago_in_words product.created_at %>
      </p>
    </article>
  <% end %>
</section>

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email, "Find out when we go live:" %>
    <%= f.text_field :email %>
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.email %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<%= render 'form' %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>